### ISSUE TITLE
Well, do they get access?!

### ISSUE THREAD

**Issue by sudokit** [bearcove/secret-fork-test#1]

**Comment by fasterthanlime** [comment]
They don't!

![image](https://github.com/bearcove/secret-fork-test/assets/7998310/2cbc8daf-1d8e-4f40-91e5-2d6361eac3bb)

https://github.com/bearcove/secret-fork-test/actions/runs/6955231962/job/18923598255?pr=2

(The docs say so, I just wanted to check by myself).
